name: LevelSaver
version: '1.0'
api-version: '1.21'
authors: [ Frodexx_UA ]
main: uadev.levelsaver.LevelSaver
description: 'Зберігання та передача рівнів досвіду'

commands:
  levelbook:
    description: Видати книгу
    usage: /levelbook [player]
    permission: levelsaver.admin
  lsreload:
    description: Перезавантажити плагін
    permission: levelsaver.admin
  withdrawlevel:
    description: Видобути банкноту досвіду
    usage: /withdrawlevel <amount>
    permission: levelsaver.player

permissions:
  levelsaver.admin:
    description: Адміністраторські права
    default: op
  levelsaver.player:
    description: Право використовувати withdrawlevel
    default: true